### ISSUE TITLE
Possible to integrate with snippets?

### ISSUE THREAD

**Issue by yangkennyk** [lostintangent/gistpad#152]
Is it possible to sync certain gist snippets with the vscode snippets feature in order to enable auto completion?

thanks!

**Comment by lostintangent** [comment]
Yeah I wonder if we can enable you to mark a gist as being a snippet, and then we automatically treat them as snippets to VS Code. Would you want to have a single gist that includes a bunch of individual snippet files? Or a bunch of individual gists, with a single file snippet in them?

**Comment by yangkennyk** [comment]
would the single gist automatically sync "snippet gists"? If not, then I think I'd prefer each snippet as it's own snippet. Although I'm not sure if that makes sense performance wise.

Whichever approach where we can mark a snippet gist as a "vs code" snippet and it auto syncs to the vs code snippet library would be nice.

maybe vs code snippets can be defined by a tag in the description or a comment in the actual snippet file?

**Comment by RandomFractals** [comment]
interesting idea. Let me know if you end up doing it and I'll add gist snippets loading to my new snippets viewer ;)

https://github.com/RandomFractals/vscode-snippets-viewer

**Comment by lostintangent** [comment]
Unfortunately, VS Code snippets need to be statically defined, and there isn't currently a way to dynamically generate them. As a result, we'll just need to reply on the current "Paste Gist File" context menu workflow. We can revisit this in the future if/when VS Code adds the necessary support. Thanks!

**Comment by mhorlacher** [comment]
Do you think we could revisit this issue @lostintangent ? My search for integrating VS Code snippets with Gists brought me to GistPad - I believe it would be a great enhancement! AFAIK Code stores snippets in a dedicated JSON file for each extension - could GitPad maintain a dictionary of gist-to-snippet entries and re-write the JSON file whenever a change is made to a gist?

**Comment by lostintangent** [comment]
@mhorlacher does the functionality of this extension look close to what you're looking for? https://marketplace.visualstudio.com/items?itemName=vaibhavacharya.gist-snip

**Comment by RandomFractals** [comment]
@lostintangent  That extension is neat! Thanks for sharing it and providing alternative solution.

**Comment by mhorlacher** [comment]
@lostintangent This look very promising, but unfortunately I couldn't make it work.
