### ISSUE TITLE
Ability to generate a git.io shortURLs for gists

### ISSUE THREAD

**Issue by rchaganti** [lostintangent/gistpad#168]
**Is your feature request related to a problem? Please describe.**
I have been using gists a lot lately and GistPad helps me manage all that without leaving the editor. I embed these gist URLs in my blog posts and reference them at several places. With the GUIDs embedded into these gist URLs, they tend to be very long. I am, at the moment, using git.io to shorten these urls and then embed into my articles. 

**Describe the solution you'd like**
Having a context menu option to "Copy GitHub short URL" will be quite useful.

**Describe alternatives you've considered**
I am using a [PowerShell module](https://github.com/rchaganti/PSGitIo) that I published for this purpose.

**Comment by lostintangent** [comment]
Adding a note to this gist that explains how to enable this: https://gist.github.com/defunkt/1209316.

**Comment by lostintangent** [comment]
Closing this for now, since we haven't seen sufficient user demand, to justify adding another menu item. If folks would like to see us prioritize this, please re-open the issue and we can discuss the appropriate UX. Thanks!
