### ISSUE TITLE
version 0.1.8 will suppress string autocompletion in Markdown

### ISSUE THREAD

**Issue by tangentyh** [lostintangent/gistpad#171]
**Describe the bug**
When this extension GistPad of version 0.1.8 and/or the extension `:emojisense:` of a recent version is enabled, string autocompletion in Markdown will be suppressed.

**To Reproduce**

0. Make sure GistPad of version 0.1.8 and `:emojisense:` of any version disabled or uninstalled
1. Enable autocompletion in Markdown with below settings
   ```json
   {
       "editor.quickSuggestions": {
           "comments": true,
           "other": true,
           "strings": true
       },
       "[markdown]": {
           "editor.quickSuggestions": true
       },
   }
   ```
2. Open any Markdown file, and the autocompletion works as the first screenshot shows, where GistPad is of version 0.1.7
3. Install or enable GistPad of version 0.1.8. Alternatively, install or enable `:emojisense:`
4. The autocompletion is now suppressed and broken, like in the second gif screenshot. You can see the string completion is suppressed almost immediately

**Expected behavior**
Autocompletion should remain intact and completions should not be suppressed.

**Screenshots**
![image](https://user-images.githubusercontent.com/13913131/87871814-42499100-c9e6-11ea-9f40-e4a07ae031ca.png)
![Jul-19-2020 17-39-14](https://user-images.githubusercontent.com/13913131/87872283-aa4da680-c9e9-11ea-8ba1-d75f43b3e547.gif)

**Desktop (please complete the following information):**

- VS Code Version v1.47.2
- GistPad Version v0.1.8

**Additional context**

1. I rely on autocompletion heavily when writing Markdown
1. Since `:emojisense:` is shipped along with this extension and can also be the culprit, it is mentioned too
3. Annoyingly, the extension "GitHub Pull Requests and Issues" can also be the culprit under some circumstances.

**Comment by lostintangent** [comment]
@tangentyh Hmm, I’m sorry you ran into this! Just to confirm: does this issue only occur if emojisense is enabled? If so, then it sounds like I should like I should remove that dependency.

**Comment by tangentyh** [comment]
@lostintangent both actually. This problem occurs if any of the below:

- GistPad v0.1.8 is enabled (v0.1.7 is fine) or
- emojisense is enabled or
- both emojisense and GistPad v0.1.8 are enabled

**Comment by bs** [comment]
I am seeing the same, but emojisense on its own is fine. It only breaks when GistPad is enabled.

Before I dive into the code, is there a place you would suggest looking to debug?

**Comment by da5is** [comment]
I'm seeing the same thin across vscode-markdown-notes and gistpad (no emojisense installed) as of 11/15/2020.

**Comment by lostintangent** [comment]
@da5is Out of curiosity: do you see this behavior if you disable GistPad, but enable vscode-markdown-notes? I’m just curious if it’s a GistPad issue, or maybe an issue with VS Code and extensions that contribute Markdown completion support.

**Comment by da5is** [comment]
I don't see the issue if GistPad is disabled but vscode-markdown-notes is enabled - just when GistPad is enabled.  Odd.

**Comment by lostintangent** [comment]
Closing this since I haven't seen any reports of the issue in a while, and I'm not sure it still repros. Please feel free to re-open it if you're still encountering this problem
