### ISSUE TITLE
Insert Snippet at the Cursor Position

### ISSUE THREAD

**Issue by hariprasadraja** [lostintangent/gistpad#210]
Opening snippets in a separate tab is annoying as I do a lot of work with snippets. I can see some of the snippets extensions are inserting the snippets directly in to the cursor position. 

I like to request the same functionality in the gistpad too.  You can bring up some setting or a keyboard shortcut to search and insert the gist at the cursor position rather than opening it in a separate tab.

**Comment by lostintangent** [comment]
If you right-click the editor and select `Paste Gist File`, that will allow you to insert a gist file at the cursor. I'm going to close this as a resolution to your request, but please re-open it if I misunderstood your scenario. Thanks!
