### ISSUE TITLE
Add Extension to Open VSX registry https://open-vsx.org/

### ISSUE THREAD

**Issue by jgarciaf106** [lostintangent/gistpad#211]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
To be able to access gistpad  from Gitpod

**Describe alternatives you've considered**
Add Extension to Open VSX registry https://open-vsx.org/

**Additional context**
N/A

**Comment by lostintangent** [comment]
Hey! Unfortunately, I don't have the bandwidth to support this extension in other distributions of VS Code. And so I'm going to close this for now, and we can reassess it later. Thanks! 👍
