### ISSUE TITLE
After creating a new file in a Gist, open it in VSCode

### ISSUE THREAD

**Issue by JasonEtco** [lostintangent/gistpad#227]
**Is your feature request related to a problem? Please describe.**

Hello! Loving GistPad, I'm not sure how it took me so long to use it! One tiny nit: when I add a new file to a Gist, I expect it to open that newly created file. I'm not able to record a GIF without showing all my Gist names 😓  so I'll outline some steps to reproduce:

* Open VSCode/GistPad extension
* Have an existing Gist (or create one)
* Add a new file to that Gist (right click, `Add new File(s)`)
* Give it a name, press Enter
* Note the toast bottom-right showing that it was created
* Observe that your VSCode editor won't have moved to that new file

**Describe the solution you'd like**

When I add a new file to a Gist, that file should be opened in my VSCode window.

**Describe alternatives you've considered**

It could be left as-is 😊 

**Additional context**

I don't know if this makes a difference, but I'm using GistPad within GitHub Codespaces. I did also verify the same behavior outside of Codespaces though.

---

Let me know how I can help! I'd be up for a PR if y'all can point me in the right direction ✨

**Comment by lostintangent** [comment]
Great suggestion! Gistpad auto-opens the file when you create a new gist, and so we should do the same thing for new files. I'll try to slip this in over the next day, and cut a release. Stay tuned!

**Comment by JasonEtco** [comment]
Thanks @lostintangent, youdabest ❤️  I'll keep my eyes peeled!

**Comment by lostintangent** [comment]
This has been resolved in v0.2.9 👍🏼

**Comment by JasonEtco** [comment]
It's true, I just tried it out and it worked like a charm. Thanks for the improvement! ✨
