### ISSUE TITLE
Interaction with local-history extension

### ISSUE THREAD

**Issue by bguisard** [lostintangent/gistpad#228]
There is an unfortunate conflict between gistpad and [local-history](https://github.com/zabel-xyz/local-history) that makes it very annoying to have both extensions enabled. In short, local-history tries to backup any files you have modified, but it's unable to find any files opened in the gistpad exetension because its unaware that they are backed by a virtual file system (see error below).

local-history has an exclude list that uses regexp to ignore files and folders, but I didn't find a way to disable it for gistpad workspaces as files are mounted using the name of the gist, which could be anything. This should probably be fixed on local-history's end, but I thought you may want to track it as part of #30. 

Another idea would be to add a `gistpad.mountFolder` to configure a prefix for your mount path, that way we can have local-history ignore any files opened by gistpad.

```
Error with copyFile: 'Error: ENOENT: no such file or directory, open '/sample_bar.vl' /sample_bar.vl => /Users/bguisard/.vscode-backups/.history/sample_bar_20210602090156.vl
```

**Comment by lostintangent** [comment]
VS Code now supports the concept of local history as a built-in feature, so I'm going to close this as won't fix, since you don't need to rely on an extension anymore. Thanks!
