### ISSUE TITLE
Open .md files

### ISSUE THREAD

**Issue by jjvillavicencio** [lostintangent/gistpad#229]
**Describe the bug**
Error when open a gist file type **.md**

**To Reproduce**
1. Go to 'Your Gists'
2. Click on 'note'
3.  Select a .md file to open
4. See error: **_Assertion Failed: argument is undefined or null._**

**Screenshots**
![image](https://user-images.githubusercontent.com/4654352/121823835-56852500-cc6d-11eb-8d93-c9cb42dded65.png)

**Desktop (please complete the following information):**
 - VS Code Version [1.58.0-insider]
 - GistPad Version [0.2.8]

**Comment by lostintangent** [comment]
I'm not able to repro this with the latest VS Code Insiders, so I'm going to close this as resolved, and assume it was a temporary regression in the insiders release. If you're able to repro this after updating your insiders install, please re-open this. Additionally, it would be helpful if you could let me know whether you're able to repro this with VS Code stable as well. Thanks!
