### ISSUE TITLE
"New CodeSwing from active CodeSwing" palette command

### ISSUE THREAD

**Issue by Sheraff** [lostintangent/gistpad#231]
**Is your feature request related to a problem? Please describe.**
CodeSwing is great to tinker and quickly try out stuff. GistPad is great to store snippets and access them later. But that's usually the order in which I do things: first I thinker, then maybe I want to keep that for later. The current workflow is the other way around: create a gist stored for later, and then tinker.

**Describe the solution you'd like**
AFAIK there can only be 1 active CodeSwing at a time in VSCode. So I'd love to be able to ⌘+⇧+P and have the command "> GistPad: new CodeSwing from current" pop up, which would move the files from the temp folder to a gist.

**Describe alternatives you've considered**
For now, all I can see as an alternative is to either
- always start by creating a gistpad, and maybe delete it later
- start with a codeswing, and if desired, copy/paste everything onto a new gistpad

**Comment by lostintangent** [comment]
Closing this as not planned
