### ISSUE TITLE
Formatter can't seem to find markdown from gistpad

### ISSUE THREAD

**Issue by Sheraff** [lostintangent/gistpad#233]
**Describe the bug**
When I try to execute the "Format Document" command (usually from the palette, but I get the same problem if I toggle "format on save" on), VS Code says there is no formatter for markdown when the .md file is from a gistpad. I don't get the same issue with other files from gistpads (.js or .css for example) and I don't get the same problem either with .md files that *aren't* from a gistpad.

**To Reproduce**
1. Execute "GistPad: New Gist" and create a *.md file
2. Add some text (or not)
3. Execute "Format Document"

<img width="512" alt="Screen Shot 2021-07-03 at 15 01 14" src="https://user-images.githubusercontent.com/1325721/124355051-893c9080-dc0f-11eb-975e-8b8fa47484e0.png">

**Desktop:**
 - VS Code Version: 1.57.1
 - GistPad Version: 0.2.9

PS: I have tried with many different formatters, just to make sure, including
- Prettier `esbenp.prettier-vscode`
- Markdown All in One `yzhang.markdown-all-in-one`
- Markdown Table Formatter `fcrespo82.markdown-table-formatter`

**Comment by lostintangent** [comment]
This issue should now be fixed, and I've been using GistPad + Prettier. Please reopen this if you're still experience issues. Thanks!

**Comment by mshick** [comment]
I'm having the same issue. On the latest version of GistPad, and have `esbenp.prettier-vscode` and `yzhang.markdown-all-in-one` installed. Formatters work in other MD files, but not the ones in GistPad.

Is some config required to set up the formatter for GistPad?
