### ISSUE TITLE
Error Forbiden signing in [Solved]

### ISSUE THREAD

**Issue by bastiano** [lostintangent/gistpad#237]
I follow the instrucction from "Getting started"
When I try to sign in with my GitHub account in order to manage my gists and repositories, I get a window with this message: 
>Oh no! An error occurred!
Please restart the sign in process from the editor.
Forbidden

* Screenshot:
[Imgur](https://imgur.com/4AFxs6t)

 - VS Codium Version  v1.58.2
 - GistPad Version  v0.3.0

- Browsers:
Chromium v92.0.4515.107
Opera v77.0.4054.277
Vivaldi v4.1.2369.11-1

- Os:
 archlinux

**Comment by lostintangent** [comment]
This sounds like an issue with VS Code's native auth, as opposed to an issue with GistPad specifically.

Are you able to log into any other extension using a GitHub identity? For example, if you tried to install and authenticate with [this extension](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github), do you encounter the same error?

**Comment by bastiano** [comment]
Thank you. You are right. It is an issue with VSCode. I get the same message with that extension too. I close this issue as solved.
