### ISSUE TITLE
Uncaught Errors: [mobx] There are multiple, different versions of MobX active. Make sure MobX is loaded only once or use `configure({ isolateGlobalState: true })`

### ISSUE THREAD

**Issue by spindensity** [lostintangent/gistpad#247]
**Describe the bug**
Click the `GistPad` extension in the `Extensions` view, in the `Runtime Status` tab, an uncaught error is raised:

```log
[mobx] There are multiple, different versions of MobX active. Make sure MobX is loaded only once or use `configure({ isolateGlobalState: true })`
```

**Screenshots**
![Snipaste_2021-09-03_01-41-21](https://user-images.githubusercontent.com/33576822/131891540-aa5a7789-e63c-42f5-950a-6ac88a3e8041.png)

**Desktop (please complete the following information):**
 - VS Code: 1.60;
 - GistPad: 0.3.0;
 - OS: Windows 10 21H1.

**Comment by spindensity** [comment]
By the way, the [GitDoc](https://github.com/lostintangent/gitdoc) extension has the same problem.

**Comment by lostintangent** [comment]
This isn't an issue with GistPad specifically, as opposed to MobX complaining that there are multiple versions of it installed. Since you opened three issues across my extensions, I'm going to close this one and track this via the CodeTour issue.
