### ISSUE TITLE
Show Hidden Files in the repository view

### ISSUE THREAD

**Issue by pomdtr** [lostintangent/gistpad#252]
**Is your feature request related to a problem? Please describe.**
I would like to manage my dotfiles from gistpad. However, hidden files are filtered out by default.

**Describe the solution you'd like**
Add a boolean setting allowing the user to show hidden file in the repository tree.

**Comment by lostintangent** [comment]
Hmm, I'm not able to repro this issue :/ I actually manage my dotfiles via GistPad and this is what I see:

![image](https://user-images.githubusercontent.com/116461/142741480-cfdf4d0a-debd-475a-a641-d2ca5a6bf7bb.png)

**Comment by lostintangent** [comment]
Closing this as "no repro" per my previous comment. Please re-open the issue if you're still experiencing an issue and can help me with repro steps. Thanks!
