### ISSUE TITLE
"New GistLog" option not shown on the sidebar.

### ISSUE THREAD

**Issue by IlanVivanco** [lostintangent/gistpad#259]
**Describe the bug**
There is no "New GistLog" option when right-clicking on the "Your Gists" section on the sidebar.

**To Reproduce**
1. Go to the GistPad tab.
2. Right-click on "Your Gists".
3. There is no "New GistLog" option.

**Expected behavior**
There should be a "New GistLog" option right under "New Secret Gist" as we can see on the [animated gif](https://user-images.githubusercontent.com/116461/70856110-fdc3a900-1e8a-11ea-8e26-2c3917e11db0.gif) on the [project's readme](https://github.com/lostintangent/gistpad#gistlog).

**Screenshots**
![image](https://user-images.githubusercontent.com/9307840/141112826-a74a3ec0-9fe8-4dc6-903a-b2b8da0aba4a.png)

**Desktop (please complete the following information):**
 - Windows 10 Pro - build 19043.1320
 - VS Code Version v1.61.2
 - GistPad Version v0.30.0

**Comment by lostintangent** [comment]
The GistLog integration is barely used, and so I actually removed that option in order to focus the menu on common actions. The `GistPad: New GistLog` command is still available in the command palette, but I've actually considered removing that as well, since it creates visual clutter when trying to create a new gist.

That said: do you commonly use the GistLog integration? I definitely need to update many of the screenshots, since I've done a decent amount of refactoring.

**Comment by IlanVivanco** [comment]
I understand, your approach seems reasonable to me, if it's not used that much, makes total sense to remove it.

I'm not a heavy user, but I've just discovered it a couple of months ago while reading your readme for another reason. 🤭

It's a very nice option for shearing a quick article with non-tech people though, or at least those who wouldn't be comfortable using the gist interface.

Do you need me to take some screenshots for you? Just let me know.

**Comment by lostintangent** [comment]
Updated screenshots would be an amazingly appreciated contribution! 😄

**Comment by IlanVivanco** [comment]
Sure thing!

A few questions though:
- Which screenshots do you need? All of the readme.md?
- What do you use for the animated ones?
- I'm on Windows, not sure if that's a problem or not.
- Any preference on dark/light theme mode?

**Comment by lostintangent** [comment]
Closing this as resolved, since we discussed not wanting to add more prominent UI for gistlog (per its small usage).
