### ISSUE TITLE
Gistpad make file corrupted on https://github.dev/

### ISSUE THREAD

**Issue by txchen** [lostintangent/gistpad#261]
**Describe the bug**
Install gistpad on vscode web version, then use it to update wiki repo's file. After saving, file content will become byte array string.

**To Reproduce**
1. Go to a gistpad-wiki repo
2. Press . go to github.dev
3. Go to gistpad extension, and open the repository.
4. Change markdown file content, and save

**Expected behavior**
It should work without damaging the file.

**Screenshots**

![image](https://user-images.githubusercontent.com/713074/143288397-528d1f6e-51d1-44a5-9fe5-ed9ef9629ee5.png)

**Desktop (please complete the following information):**
 - VS Code Version [e.g. v1.44.0]
 - GistPad Version [e.g. v0.0.66]

**Additional context**

**Comment by lostintangent** [comment]
Very weird! I can repro this issue, but it only seems to impact repo files on github.dev. Editing gists in github.dev works great, and I can edit repo files in VS Code desktop without any issues. So there must be something wrong with how I'm encoding/decoding repo files, that's buggy in the browser. I'm taking a quick look right now.

**Comment by lostintangent** [comment]
Ah yeah I can see the issue: https://github.com/lostintangent/gistpad/blob/3a0ac31478d8ecc845ad981ebe242f0bb9c98085/src/repos/store/actions.ts#L499. I updated the gist editing support to work fully in the browser, but I forgot to remove the user of `Buffer` APIs in the repo editing support. Those APIs are only exist in Node/VS Code desktop. I'll get a fix out for this later today. Thanks for reporting it!

**Comment by whilp** [comment]
I also see this on vscode.dev. Using Gistpad, when I:

1. Create a new repo
2. Add a new file (eg test.ipynb)
3. Add a cell to the notebook (eg `import os`)
4. Save the notebook

The file appears in the new repository on github.com, but the contents are rendered (by GitHub) incorrectly:

<details>
<summary>garbled contents</summary>
<pre>
123,10,32,34,99,101,108,108,115,34,58,32,91,10,32,32,123,10,32,32,32,34,99,101,108,108,95,116,121,112,101,34,58,32,34,99,111,100,101,34,44,10,32,32,32,34,101,120,101,99,117,116,105,111,110,95,99,111,117,110,116,34,58,32,110,117,108,108,44,10,32,32,32,34,109,101,116,97,100,97,116,97,34,58,32,123,125,44,10,32,32,32,34,111,117,116,112,117,116,115,34,58,32,91,93,44,10,32,32,32,34,115,111,117,114,99,101,34,58,32,91,10,32,32,32,32,34,105,109,112,111,114,116,32,111,115,34,10,32,32,32,93,10,32,32,125,10,32,93,44,10,32,34,109,101,116,97,100,97,116,97,34,58,32,123,10,32,32,34,108,97,110,103,117,97,103,101,95,105,110,102,111,34,58,32,123,10,32,32,32,34,110,97,109,101,34,58,32,34,112,121,116,104,111,110,34,10,32,32,125,44,10,32,32,34,111,114,105,103,95,110,98,102,111,114,109,97,116,34,58,32,52,10,32,125,44,10,32,34,110,98,102,111,114,109,97,116,34,58,32,52,44,10,32,34,110,98,102,111,114,109,97,116,95,109,105,110,111,114,34,58,32,50,10,125,10
</pre>
</details>

**Comment by lostintangent** [comment]
Thanks for the ping. I found the fix for this and I need to ship an update today 👍

**Comment by shanehoey** [comment]
Will 0.4.0 be published to cisual studio market place ? currently its still on 0.3.0 and hoping to have this fix

thanks

**Comment by cormil** [comment]
Hi, 
how is possible to use the version 0.4.0 on Visual Studio Web ?
Many thanks.

**Comment by shanehoey** [comment]
hey @lostintangent  any update till when 0.4.0  will be added to marketplace ?  

thanks heaps

**Comment by lostintangent** [comment]
This has now been fixed! If needed, just update to the v0.4.0 version of the extension. Thanks for the patience on this one 🙏🏼
