### ISSUE TITLE
feature request: group manager

### ISSUE THREAD

**Issue by wjx0912** [lostintangent/gistpad#263]
as the number of gist continues to grow, manage need a mass of time.

use a directory to manager all gist, some ideas for discussion:
create a manager gist item, for example: GistpadData/gistpad-sync-data.json
![1](https://user-images.githubusercontent.com/5556482/143804766-50c2cecb-fad5-4de5-bd19-40d9e9e1c118.png)

result:
![2](https://user-images.githubusercontent.com/5556482/143804784-c71db565-4f1b-43ff-876d-4e67eefe83d5.png)

the tree show in gistpad panel.

wish your reply, thanks

**Comment by RandomFractals** [comment]
related: https://github.com/lostintangent/gistpad/issues/7

**Comment by wjx0912** [comment]
@RandomFractals 
thanks anyway.
best regards~

**Comment by RandomFractals** [comment]
@wjx0912 closed so fast? happy I could help 😏
