### ISSUE TITLE
error received when I create a new Scratch note.

### ISSUE THREAD

**Issue by jpswelch** [lostintangent/gistpad#269]
I get the following error when I try to create a new Scratch note.

Error:
Error running command gistpad.newScratchNote: Unable to resolve nonexistent file 'gist://db34fece78d560c9feaa68b6e321e26a/2022-01-24.md'. This is likely caused by the extension that contributes gistpad.newScratchNote

Execute command "GistPad: New Scratch Note" or click on "+" icon to create a new scratch note.

Running:
 - VS Code Version v1.63.2 
 - GistPad Version v0.3.0

**Comment by lostintangent** [comment]
I just tried this and everything works as expected. So I may have fixed this accidentally 😄  I'm going to close this as resolved, but please re-open it if you run into this issue again. Thanks!
