### ISSUE TITLE
VS Code Comment body display change

### ISSUE THREAD

**Issue by alexr00** [lostintangent/gistpad#270]
Hello 👋

I work on the commenting API in VS Code, and I'm opening this issue because this repository contains usages of the commenting API. 

We recently noticed that even though a `Comment`'s `body` can be `string | MarkdownString` we're always displaying it as a `MarkdownString` ([issue](https://github.com/microsoft/vscode/issues/140967)). The upcoming 1.64 release will fix that: when a comment `body` is a `string` it will be displayed as a plain string and not as markdown. As a user of the the commenting API, this project may be affected by this.

If this project does wish to keep displaying comment `body` as Markdown, simply create a new `MarkdownString` and use that as the comment body:
```ts
comment.body = new vscode.MarkdownString(body);
```

It's also possible that this project doesn't rely on the incorrect display behavior and that this issue can be disregarded!

**Comment by lostintangent** [comment]
Thanks! Just updated the extension to take this change into account.
