### ISSUE TITLE
Repositories do not show content in VSCode Insiders, works fine in VSCode Stable

### ISSUE THREAD

**Issue by carlocardella** [lostintangent/gistpad#274]
**Describe the bug**
In recent builds of VSCode Insiders, GistPad Repositories no longer show the repo content (see screenshot below), VSCode Stable still works fine in the current build but if this behavior is due to some new change in Insiders, it will reach Stable soon and that may break as well. 

**To Reproduce**
1. Install VSCode Insiders
2. Just open an existing repo

**Expected behavior**
See and edit files in the repo

**Screenshots**
Problem with VSCode insiders
![image](https://user-images.githubusercontent.com/5784415/155373364-547adbec-8e8a-458e-8d16-aa0c46c4bcb2.png)

VSCode Stable works fine (for now)
![image](https://user-images.githubusercontent.com/5784415/155371744-b25f659a-b924-4305-8450-ba92ba058e32.png)

**Desktop (please complete the following information):**
 ```
Version: 1.65.0-insider (user setup)
Commit: 32456dc9e7d3194a94dd3ee0322ccf47e461d09c
Date: 2022-02-23T05:16:22.798Z
Electron: 16.0.9
Chromium: 96.0.4664.174
Node.js: 16.9.1
V8: 9.6.180.23-electron.0
OS: Windows_NT x64 10.0.22543
 ```
 - GistPad Version: v0.3.0 (should be the latest)

**Additional context**
In `Log (Window)` I found this: 

```Log
[2022-02-23 08:59:49.019] [renderer6] [error] [mobx] There are multiple, different versions of MobX active. Make sure MobX is loaded only once or use `configure({ isolateGlobalState: true })`: Error: [mobx] There are multiple, different versions of MobX active. Make sure MobX is loaded only once or use `configure({ isolateGlobalState: true })`
    at f (c:\Users\carloc\.vscode-insiders\extensions\vsls-contrib.gistfs-0.3.0\dist\extension.js:31:1156)
    at h (c:\Users\carloc\.vscode-insiders\extensions\vsls-contrib.gistfs-0.3.0\dist\extension.js:31:1116)
    at Timeout._onTimeout (c:\Users\carloc\.vscode-insiders\extensions\vsls-contrib.gistfs-0.3.0\dist\extension.js:31:16179)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```
I use the same extensions on both VSCode versions

**Comment by carlocardella** [comment]
I have found https://github.com/microsoft/codetour/issues/194, but I do not think this applies, something seems to have changed in the VSCode environment outside extensions. 

As mentioned in my initial issue, I use the same exceptions in both Stable and Insider releases, I have even exported the list (`code --list-extensions --show-versions`) and compared the two lists, they are identical, down to the version of each extension I have installed. 

So, whatever change has been made to Insiders very likely will make its way to Stable in the near future and Repositories in GistPad may be unusable

**Comment by carlocardella** [comment]
In today's Insiders this no longer reproes, I'll keep an eye on in in case it comes back or should repro on Stable

```
Version: 1.65.0-insider (user setup)
Commit: 8440b8f47231147823ba9696913d642e5f2d9d58
Date: 2022-02-25T05:17:33.544Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22543
```

**Comment by lostintangent** [comment]
Sounds good! I'm guessing it was a temporary regression in insiders that probably affected other extensions? I'm going to close this for now, and we can reopen it if it surfaces again. Thanks!
