### ISSUE TITLE
Repositories do not show content in today's Stable (1.66)

### ISSUE THREAD

**Issue by carlocardella** [lostintangent/gistpad#278]
**Describe the bug**
Seems to be a reoccurrence of #274, unfortunately this time it affects both Stable and Insiders release.
GistPad Repositories no longer show the repo content (see screenshot below).

**To Reproduce**

Install VSCode 1.66
Just open an existing repo

**Expected behavior**
See and edit files in the repo

**Screenshots**
![image](https://user-images.githubusercontent.com/5784415/160931865-00551bcb-f149-4512-93bf-c87fef43c259.png)

**Desktop (please complete the following information):**
GistPad v0.3.0

```
Version: 1.66.0 (user setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:14.623Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22000
```

**Additional context**

**Comment by carlocardella** [comment]
I'm not sure if it is related, just found this in VSCode 1.66 release notes: https://code.visualstudio.com/updates/v1_66#_remote-repositories

>Previously, the Azure Repos extension depended directly on the GitHub Repositories extension. Azure Repos and GitHub Repositories now depend on a common extension, Remote Repositories, which supports common workflows across GitHub and Azure Repos. All APIs previously exposed by the GitHub Repositories extension are now exposed by Remote Repositories.

Interesting that the API change touches the Remote Repositories area

**Comment by carlocardella** [comment]
I am trying to take a look, it seems `parent.files` here is always `undefined` but I have not yet figured out why

https://github.com/lostintangent/gistpad/blob/0f619e14e9b0540ce26f175d2b9ff2bd3603f3ed/src/repos/tree/index.ts#L56
```typescript
  getFileNodes(parent: Repository | RepositoryFile, repo: Repository) {
    return parent.files?.map((file) => new RepositoryFileNode(repo, file));
  }
```

**Comment by carlocardella** [comment]
Quick update: I have a propotype of a fix working for public repos, I need to figure out what's changed to get private repos too

**Comment by lostintangent** [comment]
What was the fix for public repos?

**Comment by carlocardella** [comment]
Do you want me to submit a PR with this first partial fix?

**Comment by carlocardella** [comment]
For private repos it looks like the token we get from 

https://github.com/lostintangent/gistpad/blob/0f619e14e9b0540ce26f175d2b9ff2bd3603f3ed/src/store/auth.ts#L61

does not have enough permission, which is odd because other extensions authorized to use my github authentication can work with private repos. Anyway, if I use the token from that call with Postman I get the same 404 error for a private repo.

**Comment by carlocardella** [comment]
It turns out there was a problem with the private repo I was using for testing 😮
I can work with other private repos just fine so I have published the PR, please take a look; for the time being I am sideloading my vsix package for day to day use till the fix will be out

**Comment by carlocardella** [comment]
> It turns out there was a problem with the private repo I was using for testing 😮

The problem is the branch: I have created a brand new private repo for testing today and the default branch on Github is now `main`, but Gispad has `master` hardcoded in a bunch of places. I'll see if I can make a fix for that as well, but in a separate PR

![image](https://user-images.githubusercontent.com/5784415/162662787-5657c131-4fee-42bf-ada7-2420bd9bf5df.png)

**Comment by carlocardella** [comment]
Uhm... it looks like, after todays Stable verision 1.66 Recovery 2, Gists are not loading anymore 😮

![image](https://user-images.githubusercontent.com/5784415/163021411-701e713c-c6f3-4912-83f9-942802c23f63.png)

**Comment by carlocardella** [comment]
Agreed, even when Repos was broken last time (and with the current issues), Gists has always worked perfectly... I don't know what chnged with this update but it feels like something in the runtime is less stable. I'll see if I can spend a bit of time on it

**Comment by carlocardella** [comment]
> > It turns out there was a problem with the private repo I was using for testing 😮
> 
> 
> 
> The problem is the branch: I have created a brand new private repo for testing today and the default branch on Github is now `main`, but Gispad has `master` hardcoded in a bunch of places. I'll see if I can make a fix for that as well
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/5784415/162662787-5657c131-4fee-42bf-ada7-2420bd9bf5df.png)
> 
> 

I just filed a separate PR (#284) for this

**Comment by valentino-90** [comment]
Hi, I have the same problem. I have private repositories with any files listed. I create them with the suffix #main because gistpad uses the master branch by default. Once the fix has been found, wouldn't it be useful to choose the default branch name from the settings panel for the next extension update?

![screen](https://user-images.githubusercontent.com/9696655/163394842-32b190b9-3229-453b-b342-ecf57c5466e8.png)

**Comment by carlocardella** [comment]
@valentino-90, with the PR I filed (#284) the default branch is read automatically from GitHub, no need to choose manually: is it ok for your use case?

**Comment by valentino-90** [comment]
@carlocardella, ok... but if i create a repository directly from GistPad (in sidebar panel), gistpad will use "master" by default. I always prefer to use "main" everywhere for compatibility with other tools, but currently i can't choose this option.

**Comment by carlocardella** [comment]
Good point, thanks, I didn't think about that (I always create my repos on GitHub first); I'll try to add it

**Comment by valentino-90** [comment]
@carlocardella great, it works because your fix is active in your case. It's ok, but in my opinion there are developers who prefer the "old" style. Maybe using **main** by default and allow the editing is a good idea for future releases. But, now the priority is the  problem of missing files in repository tree.

**Comment by lostintangent** [comment]
Your PR looks great, and I really appreciate the contribution/help here! I left a few minor comments, but we can go ahead and try to get this merged and released today 🙌
