### ISSUE TITLE
Enable (or fix) sync across devices

### ISSUE THREAD

**Issue by carlocardella** [lostintangent/gistpad#291]
**Describe the bug**
Repositories and followed users do not sync across my devices, both Stable and Insiders VSCode releases.

https://github.com/lostintangent/gistpad/blob/6bc4667eb00c09c81a852231b2f7144b86def053/src/extension.ts#L29-L30

**To Reproduce**
1. On device1 open a repo or add a new followed user
2. On device2, make sure sync is on with the same account used on device1. 
3. Wait for the devices to sync (or force a sync manually)

**Expected behavior**
When I open a repo or add a followed user on a device, the same repo or followed user should appear on other sync'ed devices automatically.

**Desktop (please complete the following information):**
 - VS Code Version [e.g. v1.66.2]
 - GistPad Version [e.g. v0.4.0]

**Comment by lostintangent** [comment]
Thanks for filing this! This actually used to work, so I'm curious what may have regressed 🤔 Looking at the VS Code API docs, the `setKeysForSync` method still appears to be valid?

**Comment by carlocardella** [comment]
Yes, that is the right method (https://code.visualstudio.com/docs/editor/settings-sync#_sync-user-global-state-between-machines), I am lookig into it

**Comment by lostintangent** [comment]
Just to confirm: did you enable syncing "UI State" in the Settings Sync config? I believe that option controls whether extension global state is synced?

**Comment by carlocardella** [comment]
Yes, I have enabled all options: 

![image](https://user-images.githubusercontent.com/5784415/164916595-6c956e93-d3ca-4dfa-845e-175bdd0b87fb.png)
