### ISSUE TITLE
How set "gistpad.apiUrl": "https://mygitserver.com/api/v3" ?

### ISSUE THREAD

**Issue by rstolpe** [lostintangent/gistpad#293]
I can't for the life of me find how to set it? I have been googling but nah, no clear instructions

**Comment by lostintangent** [comment]
Hey! This setting was actually removed a while back, since it didn't really work well, and I don't have a GitHub Enterprise account to be able to test/verify against. I didn't realize this was still in the docs/settings, so I'll take a look at removing that, to avoid confusion. Apologies!

**Comment by rstolpe** [comment]
> Hey! This setting was actually removed a while back, since it didn't really work well, and I don't have a GitHub Enterprise account to be able to test/verify against. I didn't realize this was still in the docs/settings, so I'll take a look at removing that, to avoid confusion. Apologies!

Ok, that's sad. I was hoping to use this with enterprise

**Comment by lostintangent** [comment]
Closing this as a duplicate of #96
