### ISSUE TITLE
Is there a way to set a template for daily/journal entries?

### ISSUE THREAD

**Issue by adamdoe** [lostintangent/gistpad#294]
Exactly as the title says, I'm curious if there's a way we can use a markdown file template instead of just having the date printed into the daily markdown file.

My current file prints:
`# Month day, Year`

It would be nice if it could grab a markdown template like the content below for pre-populating content in. I haven't looked into it much but does anybody know if it's possible?

```
# Month day, Year

### Reminder: work on these items this week.
[link] - link to ticket
[link] - link to ticket

### What are you thankful for today?
etc.
```

**Comment by lostintangent** [comment]
Hey! This isn't currently possible, but I think this is a great idea. I can take a look at implementing this tomorrow and report back with some feedback.
