### ISSUE TITLE
Contribute to language service extensions, so they support GistPad (e.g. Prettier)

### ISSUE THREAD

**Issue by lostintangent** [lostintangent/gistpad#30]
- [x] Markdown
- [x] Emmet
- [x] Code Spell Checker
- [x] JavaScript/TypeScript
- [x] Prettier
- [ ] [Rest Client](https://github.com/Huachao/vscode-restclient/pull/720)
- [ ] [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner)
- [ ] [SCSS Everywhere](https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion) _Note: This one is crashing GistPad_
- [ ] [Oni Snippets](https://marketplace.visualstudio.com/items?itemName=Wscats.eno)

**Comment by xavxyz** [comment]
👋, hey there!

Just discovered GistPad, this extension is excellent! And I'd love to be able to use Prettier with it.

Can I help on this feature? Any recommendations on where to start?

**Comment by xavxyz** [comment]
... I had the feeling Prettier wasn't running, but it seems to work now! 😅

Screencast:
![Screen Recording 2019-12-12 at 04 38 PM](https://user-images.githubusercontent.com/13962779/70726208-fd49d780-1cfd-11ea-9392-19842173f582.gif)

**Comment by lostintangent** [comment]
Hmm, that’s unexpected actually! Let me try this and see if Prettier works in a Gist file for me as well 😁 I was expecting to need to send a PR to that extension in order to enable it for this scenario (which should be a fairly simple change).

**Comment by lostintangent** [comment]
FYI, I just sent a PR to VS Code to enable Markdown and Emmet in Gist-backed files: https://github.com/microsoft/vscode/pull/87541.

**Comment by xavxyz** [comment]
Excellent!

**Comment by franklin-ross** [comment]
Just created an issue in the spell checker I use, which I'm guessing is also related to this. Would be great to have it supported too! I didn't realise how much I relied on spell checking in Markdown files until it was gone.

**Comment by lostintangent** [comment]
@franklin-ross Thanks! I just took a quick look at the spell checker’s code, and it’s possible that this would be an easy fix. I’ll see if I can try it out and send a PR tomorrow 👍

**Comment by franklin-ross** [comment]
Wow, that's great, thanks a lot! Impressively quick turn response time!

**Comment by lostintangent** [comment]
@franklin-ross PR is out: https://github.com/streetsidesoftware/vscode-spell-checker/pull/469.
