### ISSUE TITLE
Cannot open png images (likely other image types too)

### ISSUE THREAD

**Issue by carlocardella** [lostintangent/gistpad#304]
**Describe the bug**
Cannot open png images (likely other image types too)

**To Reproduce**
Find a Gist with a .png file, try to open it in GistPad

**Expected behavior**
Be able to see the image in VSCode editor

**Screenshots**
![image](https://user-images.githubusercontent.com/5784415/180663578-8ce8567d-f531-4ff3-859b-10b3a50d3c06.png)

**Desktop (please complete the following information):**
- Latest VSCode
- LAtest GistPad

**Additional context**

```
rejected promise not handled within 1 second: TypeError (FileSystemError): The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
c:\Users\carlo\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89
stack trace: TypeError (FileSystemError): The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
```

**Comment by carlocardella** [comment]
After some further investigation I can repro the problem only with this specific image, it may have some special encoding or something that makes it unique, I can open images in other gists just fine. 
I'll see if I can find out more.

**Comment by lostintangent** [comment]
Closing this as resolved since I haven't heard other reports of it, and you're maintaining a separate extension as well.
