### ISSUE TITLE
Understanding the usage of #tag - not grouping as expected

### ISSUE THREAD

**Issue by cdsaenz** [lostintangent/gistpad#309]
I'm trying to organize my gists according to programming language used. 
From what I've read I might use a repository but I might like to stick to gists if possible.
I think the tag solution mentioned in #7 would be great, to create a "virtual folder" by language or project.
But somehow I cannot make it work. Must be something silly I'm doing. Screenshot below of what I attempted: the tag sticks to the description but doesn't create a branch in the tree.
Thanks a lot!

![image](https://user-images.githubusercontent.com/2335805/186470054-dd8acea6-f5ca-4538-abb5-6dd0dd08b0f5.png)

**Comment by lostintangent** [comment]
The tags needs to be at the end of the gist description, and there needs to be a space between the description and the hash mark. So "foo #bar" would put that gist into a group called "bar.

In your screenshot, there isn't a space before the hash, which would prevent it from being picked up as a tag. So I'm going to close this as resolved, but let me know if it doesn't work when you add the space 👍

**Comment by cdsaenz** [comment]
Thanks a lot @lostintangent ! That was it! Here testing with `snip1 #javalang` and `test2 #javalang` and it works perfect. Great stuff.
![image](https://github.com/lostintangent/gistpad/assets/2335805/76247747-4085-4e4b-91c7-31c73f75feea)
