### ISSUE TITLE
Can you sync gistpad with local version of the repo as well?

### ISSUE THREAD

**Issue by gal064** [lostintangent/gistpad#313]
My use case is this:
I have a repo with my notes using Foam. In this repo I also have a [todo.txt](https://todotxt.org) file which I manage through a CLI. Is there an option to connect GistPad to a local clone of a repo so I can edit the todo.txt file with the CLI?

Alternatively, somehow connect the CLI to GistPad?

**Comment by lostintangent** [comment]
Syncing gists with a local directory/file is outside of the current scope of this extension. So I'm going to close this as "not planned" since I unfortunately won't have the capacity to maintain this capability. Thanks for the feedback 🙏
