### ISSUE TITLE
Logout Feature

### ISSUE THREAD

**Issue by lxchurbakov** [lostintangent/gistpad#321]
Hey @lostintangent !

I think it would be nice to introduce logout button. I am stuck with this situation when the token (or whatever GistPad is storing to access github gists) is invalid, but the app still keeps trying to use it. There is no way to stop it from doing so - reinstalling with (or without) reloading does not help.

**Additional context**

Firstly mentioned here, but this did not work for me: https://github.com/lostintangent/gistpad/issues/199

**Comment by lostintangent** [comment]
Hey! Yeah I need to add this. I can get to it this week and will ping you when it's published to the marketplace. Thanks for the feedback 👍

**Comment by lcenchew** [comment]
Having the same issue. Any work around until it is published?

**Comment by oxpayken** [comment]
> Any work around 

Created a separate [Profile in VS Code
](https://code.visualstudio.com/docs/editor/profiles).

**Comment by lostintangent** [comment]
FYI VS Code doesn't support extensions programmatically logging the user out. So I'm not able to do this at the moment :/
