### ISSUE TITLE
Sign out/revoke access

### ISSUE THREAD

**Issue by parksj10** [lostintangent/gistpad#326]
Is there no way to revoke github access to the plugin once it is installed? I can't find a sign out/revoke option anywhere

**Comment by carlocardella** [comment]
You can deauthorize extensions from VSCode:

![deauthorize gistpad](https://user-images.githubusercontent.com/5784415/217335987-946feab0-bd67-4576-85d7-48006569fd78.gif)

**Comment by parksj10** [comment]
dope, that was a fast response. Thanks a lot!
