### ISSUE TITLE
gistpad fails to load in github.dev

### ISSUE THREAD

**Issue by cori** [lostintangent/gistpad#327]
**Describe the bug**

Gistpad fails to load in github.dev.

**To Reproduce**
(these were **my**) Steps to reproduce the behavior:
1. Open github.dev to load the web editor with gistpad installed (I'm doing so by using settings sync)
2. Attempt to signin using GitHub in the gistpad sidebar
3. Observe no response from clicks
4. Disable gistpad
5. Open the dev console
6. reenable gistpad
7. observe several console errors (the most relevant-seeming one is included below)

**Expected behavior**
Gistpad is enabled and functional

**Desktop (please complete the following information):**
 - VS Code Version [e.g. v1.44.0]

```
Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:27:50.904Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15
```

 - GistPad Version [e.g. v0.0.66]
v0.4.1

**Additional context**

```
[Error] Activating extension 'vsls-contrib.gistfs' failed: Invalid regular expression: invalid group specifier name.
	(anonymous function) (workbench.web.main.js:2049:25748)
	asyncFunctionResume
	M (workbench.web.main.js:1604:14947)
	H (workbench.web.main.js:1604:14040)
	G (workbench.web.main.js:1604:13021)
	invoke (workbench.web.main.js:83:150)
	deliver (workbench.web.main.js:83:2036)
	fire (workbench.web.main.js:83:1675)
	(anonymous function) (workbench.web.main.js:1583:17912)
```

**Comment by cori** [comment]
This may be browser-related - it seems as though I'm able to log in via gistpad using github.dev / vscode.dev in Chrome, but in Safari it's unresponsive.

**Comment by ItalyPaleAle** [comment]
I have the same issue on vscode.dev using Safari on iPad

**Comment by lostintangent** [comment]
GitHub.dev hasn't really been maintained and I almost never used it anymore. So I'm going to close this as "not planned" since I unfortunately don't have the time to support it :/ But I'd be more than happy to accept PRs if others had the capacity to contribute here.
