### ISSUE TITLE
[FR]: tracking uncommited changes and upload to github/gist

### ISSUE THREAD

**Issue by tbennett6421** [lostintangent/gistpad#333]
**Describe the solution you'd like**
It would be nice to have changes tracked and have the ability to update a gist on GitHub.
Perhaps a command palette command to update the gist.

**Additional context**
see the following for context.
<img width="1438" alt="image" src="https://github.com/lostintangent/gistpad/assets/6843296/cd0697d7-9c1e-4506-a1f4-07b9509fb547">

<img width="769" alt="image" src="https://github.com/lostintangent/gistpad/assets/6843296/6dcd8626-abfe-4201-870e-b22899f11b5b">

**Comment by lostintangent** [comment]
Hey! Thanks for the feedback. Unfortunately this kind of capability is outside the scope of the extension, since it's meant for editing gists as "commit on save" documents, as opposed to explicitly tracking changes and committing them when ready.

So I'm going to close it as "not planned". Thanks!
