### ISSUE TITLE
Extension sadly stopped working. 

### ISSUE THREAD

**Issue by konfuzius** [lostintangent/gistpad#337]
"Loading gists..." in loop.

"Error running command gistpad.refreshShowcase: Remote end closed socket abruptly.. This is likely caused by the extension that contributes gistpad.refreshShowcase."

_Tested with new created GH token.
Already reinstalled extension.
Tested on fresh VSCode.
"GitHub Gist Explorer" Extension works again._

**Comment by lostintangent** [comment]
Hmm I'm not able to repro this 🤔 

Did you say you were able to work around it by signing out and back into GH?

**Comment by planetf1** [comment]
++ just came here after trying gistpad for the first time. In my case I am unable to sign in -- I get the browser popup (macos - can be safari or chrome), but the 'signing in to github.com' pop up pane never disappears

**Comment by lostintangent** [comment]
Seems to be working great for me as well. So I'm going to close this as no-repo. Let me know if you run into any issues. Thanks!
