### ISSUE TITLE
I would love to be able to edit discussions from within VSCode

### ISSUE THREAD

**Issue by asilverman** [lostintangent/gistpad#338]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to edit a discussion post from within the browser, its cumbersome and would love to be able to do it from within my IDE

**Describe the solution you'd like**
GistPad allows me to open, edit and publish the discussion post as I edit it

**Describe alternatives you've considered**
Search the internet and found nothing for this workflow

**Additional context**

**Comment by lostintangent** [comment]
I've considered doing this, but I also wonder if it's best handled by a separate extension? GistPad is currently focused on editing files (in gists and repos), and comments on code. Whereas Discussions isn't file based, and so the UX and scenarios would be completely different 🤔

**Comment by lostintangent** [comment]
Closing this as not planned, due to the above comment.
