### ISSUE TITLE
Repo is not getting created with template

### ISSUE THREAD

**Issue by th-shubham** [lostintangent/gistpad#340]
**Describe the bug**
'New Repo from Template' option is not creating a repo

**To Reproduce**
1. Go to GistPad from Primary Side Bar
2. Click on 'Open Repository' from Repositories Section
3. Select '+ Create Repo from Template...' from command panel
4. See if repo is created, it won't

**Expected behavior**
Repo is expected to get created with template as well.

**Desktop (please complete the following information):**
 - VS Code Version [e.g. v1.82.2(Universal)]
 - GistPad Version [e.g. v0.4.1]

**Additional context**
The other selection '+ Create Repo' from command panel works fine.

**Comment by lostintangent** [comment]
This is fixed in the latest extension release
